In [2]:
import torch

### Empy tensor

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  1.5846e+29, -5.2339e+10],
        [-2.0005e+00,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


### Randomly initialized tensor

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2696, 0.9829, 0.9826],
        [0.3010, 0.5266, 0.7160],
        [0.8400, 0.8191, 0.8458],
        [0.9739, 0.3143, 0.8632],
        [0.4875, 0.9109, 0.7614]])


In [6]:
### matrix filled zeors and of dtype long

In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
### construct a tensor direclty from data

In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
### create a tensor on the basie of existing tensor. 
##### These methods will reuse the properties of the input tensor, e.g. dtype, unless new values are provided by user

In [11]:
# new_* methods take in sizes
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# override dtype!
# result has the same size
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2417,  0.1468,  1.6453],
        [ 1.4253, -1.0601,  1.2554],
        [-0.7824,  1.1753,  0.5874],
        [-0.6122,  0.0981, -0.2005],
        [ 0.1118, -1.4932, -1.2615]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [15]:
### Operations

#### Addition syntax 1

In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0870,  0.3514,  2.2075],
        [ 2.3269, -0.8011,  1.9043],
        [-0.5564,  1.6305,  1.1717],
        [-0.3641,  0.6415,  0.3838],
        [ 0.4361, -0.7478, -1.2049]])


In [16]:
#### Addition syntax 2

In [17]:
print(torch.add(x, y))

tensor([[ 1.0870,  0.3514,  2.2075],
        [ 2.3269, -0.8011,  1.9043],
        [-0.5564,  1.6305,  1.1717],
        [-0.3641,  0.6415,  0.3838],
        [ 0.4361, -0.7478, -1.2049]])


In [18]:
#### providing an output tensor as an argument

In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0870,  0.3514,  2.2075],
        [ 2.3269, -0.8011,  1.9043],
        [-0.5564,  1.6305,  1.1717],
        [-0.3641,  0.6415,  0.3838],
        [ 0.4361, -0.7478, -1.2049]])


In [21]:
#### Addition in place 

In [22]:
y.add_(x)
print(y)

tensor([[ 1.0870,  0.3514,  2.2075],
        [ 2.3269, -0.8011,  1.9043],
        [-0.5564,  1.6305,  1.1717],
        [-0.3641,  0.6415,  0.3838],
        [ 0.4361, -0.7478, -1.2049]])


In [23]:
#### Any operation that mutates a tensor in-place is post-fixed with an '_'. eg: x.copy_(y), x.t_() will change x

In [24]:
#### You can use standard numpy like indexing like

In [25]:
print(x[:, 1])

tensor([ 0.1468, -1.0601,  1.1753,  0.0981, -1.4932])


In [26]:
#### Resizing can be done by torch.view

In [27]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
