In [26]:
import torch

### Empy tensor

In [27]:
x = torch.empty(5, 3)
print(x)

tensor([[2.3793e-23, 4.5705e-41, 5.8759e-03],
        [3.0697e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.8788e+31, 1.7220e+22],
        [3.7771e-08, 7.0648e-10, 2.9245e-06]])


### Randomly initialized tensor

In [28]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7294, 0.9992, 0.0505],
        [0.1505, 0.1287, 0.2587],
        [0.0830, 0.2288, 0.0231],
        [0.9840, 0.7220, 0.9028],
        [0.3001, 0.1134, 0.5611]])


### matrix filled zeors and of dtype long

In [29]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### construct a tensor direclty from data

In [30]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


### create a tensor on the basie of existing tensor. 
##### These methods will reuse the properties of the input tensor, e.g. dtype, unless new values are provided by user

In [31]:
# new_* methods take in sizes
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# override dtype!
# result has the same size
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6572,  0.4973, -0.6879],
        [-0.2817,  0.2660, -1.1200],
        [ 0.0602, -1.7531,  0.4945],
        [ 0.1978, -0.5046, -1.8279],
        [-0.2544, -0.7368, -0.9340]])


In [32]:
print(x.size())

torch.Size([5, 3])


### Operations

#### Addition syntax 1

In [33]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8178,  0.7699,  0.2146],
        [ 0.5798,  0.8491, -0.8404],
        [ 0.2111, -1.4543,  0.7494],
        [ 0.9119, -0.2906, -1.0511],
        [ 0.3443,  0.0189, -0.6802]])


#### Addition syntax 2

In [34]:
print(torch.add(x, y))

tensor([[ 0.8178,  0.7699,  0.2146],
        [ 0.5798,  0.8491, -0.8404],
        [ 0.2111, -1.4543,  0.7494],
        [ 0.9119, -0.2906, -1.0511],
        [ 0.3443,  0.0189, -0.6802]])


#### providing an output tensor as an argument

In [35]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8178,  0.7699,  0.2146],
        [ 0.5798,  0.8491, -0.8404],
        [ 0.2111, -1.4543,  0.7494],
        [ 0.9119, -0.2906, -1.0511],
        [ 0.3443,  0.0189, -0.6802]])


#### Addition in place 

In [36]:
y.add_(x)
print(y)

tensor([[ 0.8178,  0.7699,  0.2146],
        [ 0.5798,  0.8491, -0.8404],
        [ 0.2111, -1.4543,  0.7494],
        [ 0.9119, -0.2906, -1.0511],
        [ 0.3443,  0.0189, -0.6802]])


#### Any operation that mutates a tensor in-place is post-fixed with an '_'. eg: x.copy_(y), x.t_() will change x

#### You can use standard numpy like indexing like

In [37]:
print(x[:, 1])

tensor([ 0.4973,  0.2660, -1.7531, -0.5046, -0.7368])


#### Resizing can be done by torch.view

In [38]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy Bridge

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [41]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [42]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [43]:
## let us run this cell only if CUDA is available 
# We will use ''torch.device'' objects to move tensors in and out of GPU 
if torch.cuda.is_available():
    device = torch.device("cuda")                        # a CUDA Device object
    y = torch.ones_like(x, device=device)                # directly create a tensor on GPU
    x = x.to(device)                                     # or just use strings to CUDA
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))                     # to can also change dtype together

tensor([[-0.2291,  0.0064,  0.6780,  1.1199],
        [-0.2729,  1.0505,  2.1116,  1.1874],
        [ 2.6810,  1.4325,  0.6940,  2.1699],
        [ 1.7469,  0.4794, -0.3538,  0.7825]], device='cuda:0')
tensor([[-0.2291,  0.0064,  0.6780,  1.1199],
        [-0.2729,  1.0505,  2.1116,  1.1874],
        [ 2.6810,  1.4325,  0.6940,  2.1699],
        [ 1.7469,  0.4794, -0.3538,  0.7825]], dtype=torch.float64)


## AUTOGRAD Automatic differentiation